version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_DB: stockhouse_db
    ports:
      - "9999:8080"
    depends_on:
      - database

  database:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stockhouse_db
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "--quiet"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data: