apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: stock-house
type: Opaque
data:
#  DATABASE_NAME: {{ .Values.service.db.dbname | b64enc }}
  POSTGRES_PORT: {{ .Values.service.db.sport | b64enc }}
  POSTGRES_HOST: {{ .Values.service.db.host | b64enc }}
  POSTGRES_DB: {{ .Values.service.db.dbname | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.service.db.password | b64enc }}
  POSTGRES_USER: {{ .Values.service.db.username | b64enc }}
