spring:
  application:
    name: "StockHouse"
  profiles:
    active: @spring.profiles.active@
  batch:
    job:
      enabled: false

springdoc:
  api-docs:
    path: "/api-docs"

app:
  scheduling:
    mode: none # none, simple, optimised, batch
    delay: 600000 #ms
    exclusive_lock: false
    output_file: test.txt
    priceIncreasePercentage: 12.5
rest:
  currency-service:
    host: "http://localhost:8081"
    methods:
      get-currency: "/api/v1/currency"
    mock:
      enabled: true
