spring:
  application:
    name: "StockHouse"
  profiles:
    active: @spring.profiles.active@
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
springdoc:
  api-docs:
    path: "/api-docs"
