spring:
  application:
    name: "StockHouse"
  profiles:
    active: @spring.profiles.active@
  batch:
    job:
      enabled: false
springdoc:
  api-docs:
    path: "/api-docs"

app:
  scheduling:
    mode: simple # none, simple, optimised, batch
    delay: 600000 #ms
    exclusive_lock: false
    output_file: test.txt
    priceIncreasePercentage: 12.5
rest:
  currency-service:
    host: "http://localhost:8081"
    methods:
      get-currency: "/api/v1/currency"
    mock:
      enabled: true
  account-service:
    host: "localhost:8081"
    methods:
      get-account-numbers:
        "/api/v1/account-numbers"
    mock:
      enabled: true
  crm-service:
    host: "localhost:8082"
    methods:
      get-inn:
        "/api/v1/inn"
    mock:
      enabled: true